{{- range $color := .Values.blueGreen.colors }}
{{- $cfg := index $.Values.deployments $color }}
{{- if $cfg.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" $ }}-{{ $color }}
  labels:
    app.kubernetes.io/name: {{ include "django-app.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    color: {{ $color }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-app.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      color: {{ $color }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-app.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        color: {{ $color }}
    spec:
      serviceAccountName: {{ include "django-app.serviceAccountName" $ }}
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: app
          image: "{{ $.Values.image.repository }}:{{ $cfg.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            {{- toYaml $.Values.env | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
---
{{- end }}
{{- end }}