apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "django-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    color: {{ .Values.service.activeColor }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http