apiVersion: v1
kind: Service
metadata:
  # Stable name â€” traffic flips via selector, not via new Services
  name: {{ include "django-app.fullname" . }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
    color: {{ .Values.color }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "django-app.selectorLabels" . | nindent 4 }}
    color: {{ .Values.color }}