apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-app
spec:
  rules:
    - host: django.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-blue-django-app-blue
                port:
                  number: 8000
