apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-app-staging
spec:
  rules:
    - host: django-staging.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-green-django-app-green
                port:
                  number: 8000
